### ISSUE TITLE
Conda cache

### ISSUE THREAD

**Issue by josecelano** [josecelano/data-version-control#1]
We added a task to the main workflow to use the cache for conda packages:

```
      - name: Cache Conda
        uses: actions/cache@v2
        if: ${{ !env.ACT }} # It seems cache doesn't work locally using act. Error: Attempt 1 of 2 failed with error: Cache Service Url not found, unable to restore cache.
        env:
          # Increase this value to reset cache if environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}
```

We followed the instructions from the [official documentation of the GitHub Action](https://github.com/marketplace/actions/setup-miniconda#caching) but It seems it's not working because it takes the same time for the workflow task to setup conda (approx 3m).

This is the way GitHub restores the cache
```
/usr/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/0ab39142-6d27-4ba5-9746-1666e1aed07a/cache.tzst -P -C /home/runner/work/data-version-control/data-version-control
```

And this is how conda setup defines the cache dir:
```
/usr/share/miniconda3/condabin/conda config --add pkgs_dirs /home/runner/conda_pkgs_dir
```

Apparently, both dirs do not match.
